dist: xenial
language: python
python:
  - "3.7"

sudo: false
cache: pip

install:
  - pip install sphinx~=3.2.1
  - pip install sphinx-rtd-theme~=0.5.0

script: cd docs && sphinx-build -nWT -b dummy . _build/html
